# Generated by Django 5.2.14 on 2026-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Raw English legal query')),
                ('expanded_query', models.TextField(blank=True, help_text='German+English expanded query')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Running'), ('SUCCESS', 'Complete'), ('FAILURE', 'Failed')], default='PENDING', max_length=20)),
                ('citations_json', models.TextField(blank=True, help_text='JSON list of predicted citations')),
                ('results_json', models.TextField(blank=True, help_text='JSON list of full reranked results')),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('precision_score', models.FloatField(blank=True, null=True)),
                ('recall_score', models.FloatField(blank=True, null=True)),
                ('hybrid_tor_k', models.IntegerField(default=100)),
                ('reranker_top_k', models.IntegerField(default=10)),
                ('use_stage2', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_secs', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Query Run',
                'ordering': ['-created_at'],
            },
        ),
    ]
