# Generated by Django 5.2.14 on 2026-05-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queryrun',
            old_name='hybrid_tor_k',
            new_name='hybrid_top_k',
        ),
        migrations.AlterField(
            model_name='queryrun',
            name='citations_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queryrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='queryrun',
            name='expanded_query',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queryrun',
            name='results_json',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='queryrun',
            name='task_id',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True),
        ),
    ]
