# Generated by Django 5.2.14 on 2026-05-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_web', '0002_rename_hybrid_tor_k_queryrun_hybrid_top_k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryrun',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
